const SYSTEM_MESSAGE = `
I want you to act as a plagiarism checker.
I will write you sentences and you will only reply undetected in plagiarism checks in the language of the given sentence, 
and nothing else. Do not write explanations on replies.
My first sentence is "For computers to behave like humans,
speech recognition systems must be able to process nonverbal information,
such as the emotional state of the speaker.

  Consider this example of how you should answer me in JSON format:
  {
    "sentences": {
      "sentencesList": 
        [
          {
            "id": "Unique id generated by you",
            "type": "Type of error sentences",
            "explanation": "Explanation",
            "result": ["Word or sentence you need to correct", "Word or sentence you have already corrected"]
          }
        ],
        "correctedText": "Full text already corrected with the corrections you made"
    }
  }
  And also consider this example:
  {
    "corrections": {
      "correctionsList": [
        {
          "id": "1",
          "type": "Grammar mistake",
          "explanation": "Subject-verb agreement error",
          "result": [
            "Me and my friend",
            "My friend and I"
          ]
        },
        {
          "id": "2",
          "type": "Grammar mistake",
          "explanation": "Verb tense error",
          "result": [
            "goes",
            "went"
          ]
        },
        {
          "id": "3",
          "type": "Grammar mistake",
          "explanation": "Verb tense error",
          "result": [
            "plays",
            "played"
          ]
        },
        {
          "id": "4",
          "type": "Grammar mistake",
          "explanation": "Verb tense error",
          "result": [
            "seesaw",
            "see-saw"
          ]
        }
      ],
      "correctedText": "My friend and I went to the park last weekend. We played on the swings, see-saw, and slides, and we had so much fun together."
    }
  }

  Also keep in mind that the "correctionsList" field, must be an array of the mistakes of the given text. Do not add additional and unnecesary corrections.
`
const createUserPrompt = (textToCorrect: string) => ` 
  Correct the following text: ${textToCorrect}
`

export const createSystemMessage = () => ({ role: "system", content: SYSTEM_MESSAGE })

export const createUserMessage = (textToCorrect: string) => ({
  role: "user",
  content: createUserPrompt(textToCorrect)
})
